### ISSUE TITLE
Open `.ai.change` permission for personal usage

### ISSUE THREAD

**Issue by NeumoNeumo** [Jayfeather233/shinxbot2#1]
Thanks for your marvelous job to integrate GPT3.5 into shinx :laughing: 
It is reasonable to restrict the permission of the command `.ai.change` in the group because it will make the bot behave like what the op wants. However, when contact with the shinx personally, we do need to have the permission to change the mode, at least to disable all the pre-prompt by default, for better user experience.
For example, I worried that the translation between languages would impair the accuracy of the technical information in the conversation. But the default mode seems to speak Chinese. And I do not have the permission to disable such a feature.

感谢大大将GPT3.5整合进了shinx :laughing: 
在群聊中对`.ai.change`的使用权进行限制是合理的，因为这样我们就可以让shinx在群中发挥特定的作用（比如让它做个宝可梦）。但是在私聊中，我们可能确实需要改变模式的能力，或至少能够去除默认的提示语前缀。
比如，我担心中英转换会影响GPT3.5表意的准确性，因此我用英文对话并希望获得技术支持，但默认模式下，shinx是说中文的小猫怪...

**Comment by Jayfeather233** [comment]
已更改
