### ISSUE TITLE
Use better backends in place of `go-cqhttp`

### ISSUE THREAD

**Issue by NeumoNeumo** [Jayfeather233/shinxbot2#12]
As mentioned in [this issue](https://github.com/Mrs4s/go-cqhttp/issues/2471), `go-cqhttp` has been strictly regulated by Tencent. As a result, `shinx` suffers from being blocked after a limited quota of messages sent in a QQ group. Therefore, a better backend is imperative to be applied for `shinx`.

Potential backends:
- https://github.com/whitechi73/OpenShamrock
- https://github.com/LagrangeDev/Lagrange.Core

**Comment by Jayfeather233** [comment]
changed to lagrange
