### ISSUE TITLE
Set git submodules always to the master branch

### ISSUE THREAD

**Issue by NeumoNeumo** [Jayfeather233/shinxbot2#9]
I notice that `shinxbot2` retains specific checkouts of its submodules (as shown below) lagging behind the master/main branch development that fixes potential bugs.
```bash
Submodule path 'lib/CImg': checked out 'b99d58d9660f82c7c848e58768b85da01286c512'
Submodule path 'lib/base64': checked out 'db7c6834bd4f733899bd93218926247a659d8924'
```

So, a probably helpful suggestion is to set git submodules always to the master branch instead. Details may be found [here](https://stackoverflow.com/a/17850022/17792535).

**Comment by Jayfeather233** [comment]
Thank you. Fixed that.
